name: "CI - Bump Version"

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  bump-version:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release-')
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout main
        uses: actions/checkout@v6
        with:
          ref: main
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Configure git user and email
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "Github Action"    

      - name: Delete Release Branch
        run: |
           echo "Deleting branch: ${{ github.head_ref }}"
           gh api -X DELETE /repos/${{ github.repository }}/git/refs/heads/${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump to the next snapshot version
        run: |
          echo "Bump the maven pom.xml version"
          mvn -ntp -B versions:set versions:commit -DnextSnapshot=true -DprocessAllModules=true -DprocessParent
          NEW_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          
          echo "Bump the yaml rules containing the snowdrop openrewrite recipes jar too"
          find cookbook/rules -name "*.yaml" -exec sed -i "s|dev.snowdrop.mtool:openrewrite-recipes:[0-9.]*\(-SNAPSHOT\)\{0,1\}|dev.snowdrop.mtool:openrewrite-recipes:$NEW_VERSION|g" {} +
          find tests/src/test/resources/cookbook -name "*.yaml" -exec sed -i "s|dev.snowdrop.mtool:openrewrite-recipes:[0-9.]*\(-SNAPSHOT\)\{0,1\}|dev.snowdrop.mtool:openrewrite-recipes:$NEW_VERSION|g" {} +
          
          git add .
          git commit -m "chore: Bump the project to version: $NEW_VERSION [skip ci]"
          git push origin main